fix helm3 not respecting HPA replicas
orchestracities/charts pull request #89
Opened 2020-12-18 11:53 UTC by Durburz

Helm3 replaces the replica count set by the HPA repeatedly, resulting in a up- and down-scaling loop.

Because of that it is necessary to update the helm charts.
https://github.com/helm/helm/issues/7090

2020-12-18 11:58 UTC, chicco785 commented
@Durburz for the release to work, you need to increase the chart version in the different `Chart.yaml` files

2020-12-18 11:59 UTC, chicco785 requested changes
increase the chart version in the different Chart.yaml files

2020-12-18 13:59 UTC, chicco785 approved these changes
LGTM

2020-12-23 09:24 UTC, chicco785 commented
@Durburz the PR is stale since I am waiting a reply on the not triggered build from travis-ci team

2021-01-04 08:25 UTC, Durburz commented
@chicco785 is there anything further I can do get this request merged?

2021-01-12 12:55 UTC, chicco785 commented
so travis team reported that ci-branch now works only for branches in the same repo, that's why it was not launched. I will force merge and disable the check.

2021-01-12 12:56 UTC, merged